# Generated by Django 3.2 on 2021-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifier',
            options={'verbose_name': '待分类图片', 'verbose_name_plural': '待分类图片'},
        ),
        migrations.AlterField(
            model_name='classifier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='文件名称'),
        ),
        migrations.AlterModelTable(
            name='classifier',
            table='Img',
        ),
    ]
